spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sprint3}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:admin}
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: monolith
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init.sql

server:
  port: 8080
  
  
springdoc:
  api-docs:
    path: /api-docs

